# =============================================================================
# SmartPeças ERP - docker-compose.yml (Estrutura Monorepo)
# =============================================================================
# Arquivo: /smartpecas/docker-compose.yml
#
# Descrição: Orquestra os serviços para o ambiente de DESENVOLVIMENTO,
# com hot-reload para o backend e healthcheck para o banco de dados.
#
# Versão: 2.1 (Desenvolvimento)
# Equipe SmartPeças
# Atualizado em: 22/07/2025
# =============================================================================

services:
  db:
    image: postgres:15-alpine
    container_name: smartpecas_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: . # Constrói a partir da raiz
    container_name: smartpecas_backend
    command: npm run start:backend # Roda o script definido no root package.json
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mapeia as pastas necessárias para o hot-reload
      - ./packages/backend:/usr/src/app/packages/backend
      - ./prisma:/usr/src/app/prisma
      # Exclui a node_modules para usar a do contêiner
      - /usr/src/app/node_modules

volumes:
  postgres_data:
